Makefile, charts/README.md, charts/ks-devops/charts/s2i/crds/devops.kubesphere.io_s2ibinaries.yaml, charts/ks-devops/charts/s2i/crds/devops.kubesphere.io_s2ibuilders.yaml, charts/ks-devops/charts/s2i/crds/devops.kubesphere.io_s2ibuildertemplates.yaml, charts/ks-devops/charts/s2i/crds/devops.kubesphere.io_s2iruns.yaml, charts/ks-devops/crds/devops.kubesphere.io_devopsprojects.yaml, charts/ks-devops/crds/devops.kubesphere.io_pipelines.yaml, hack/fetch-crds.sh
See the description about this PR from README files.
=> Update CRDs and provide a script to fetch CRDs

charts/ks-devops/charts/s2i/templates/java.yaml, charts/ks-devops/charts/s2i/templates/tomcat.yaml
See https://github.com/kubesphere/s2ioperator/pull/158
=> Add two more maven related envs

charts/ks-devops/charts/jenkins/values.yaml
With this feature, we can provide multiple Jenkins config files.
* https://github.com/jenkinsci/configuration-as-code-plugin/pull/1218
=> Support Jenkins configruation merge strategy

charts/ks-devops/crds/devops.kubesphere.io_pipelineruns.yaml
Synchronize PipelineRun CRD.
Please see https://github.com/kubesphere/ks-devops/pull/238.
Upstream PR: https://github.com/kubesphere/ks-devops/pull/239.
=> Synchronize PipelineRun CRD

charts/ks-devops/Chart.yaml, charts/ks-devops/templates/cronjob-gc.yaml, charts/ks-devops/values.yaml
Upstream is https://github.com/kubesphere/ks-devops/pull/237
=> Add a cronjob to gc PipelineRuns

charts/ks-devops/crds/devops.kubesphere.io_pipelineruns.yaml, charts/ks-devops/crds/devops.kubesphere.io_pipelines.yaml
Add age as the additional print column
=> Update CRDs of pipeline and pipelinerun

charts/ks-devops/charts/jenkins/values.yaml
fix https://github.com/kubesphere-sigs/ks-devops-helm-chart/issues/18
Please see the result with this PR:
=> Avoid always create jenkins admin user

charts/ks-devops/Chart.yaml
Before we have a new release. Please merge https://github.com/kubesphere-sigs/ks-devops-helm-chart/pull/17 first
=> Bump ks-devops helm chart to 0.1.4

charts/ks-devops/charts/jenkins/values.yaml, charts/ks-devops/charts/s2i/values.yaml
Upgrade versions of dependencies for v3.2.0.
/kind chore
=> Upgrade versions of dependencies for v3.2.0

charts/ks-devops/charts/jenkins/values.yaml
Signed-off-by: Daniel Hu <farmer.hutao@outlook.com>
see below
https://github.com/kubesphere/ks-installer/pull/1831#pullrequestreview-817895938
=> Adjust default xmx/xms configuration at jenkins-values.yaml

charts/ks-devops/Chart.yaml
Signed-off-by: John Niang <johnniang@fastmail.com>
=> Bump up ks-devops charts for next release

charts/ks-devops/charts/s2i/crds/devops.kubesphere.io_s2ibuildertemplates.yaml, charts/ks-devops/crds/devops.kubesphere.io_pipelineruns.yaml, charts/ks-devops/crds/devops.kubesphere.io_pipelines.yaml, charts/ks-devops/crds/devops.kubesphere.io_templates.yaml, hack/fetch-crds.sh
This PR fetches Template CRD according to https://github.com/kubesphere-sigs/ks-devops-helm-chart/blob/8f18c01240a123f084e6a285f5966820353d8046/charts/README.md?plain=1#L1-L6
/kind chore
=> Fetch templates.devops.kubesphere.io CRD

charts/ks-devops/crds/devops.kubesphere.io_devopsprojects.yaml, hack/fetch-crds.sh
I did two things in this PR:
* Update the CRD of the DevOpsProject
* See also https://github.com/kubesphere/ks-devops/pull/463
* Fix the bash script `fetch-crds.sh`
=> Update the CRD of the DevOpsProject

charts/ks-devops/crds/devops.kubesphere.io_clustertemplates.yaml, hack/fetch-crds.sh
- This PR fetches Template CRD according to https://github.com/kubesphere-sigs/ks-devops-helm-chart/blob/8f18c01240a123f084e6a285f5966820353d8046/charts/README.md?plain=1#L1-L6
- Fix redirect problem when using curl command in fetch script.
/kind chore
=> Fetch clustertemplates.devops.kubesphere.io CRD

charts/ks-devops/crds/devops.kubesphere.io_clustertemplates.yaml, charts/ks-devops/crds/devops.kubesphere.io_templates.yaml, charts/ks-devops/templates/cluster-template-ci.yaml, charts/ks-devops/templates/cluster-template-cicd.yaml
1. Update Template and ClusterTemplate CRDs, see https://github.com/kubesphere/ks-devops/pull/477 for more.
2. Update ci and cicd templates due to CRD updated.
/kind chore
=> Update Template and ClusterTemplate CRDs

charts/ks-devops/templates/cluster-template-ci.yaml
Typo fix: discription to description.
/kind chore
=> Typo fix: discription to description

Makefile, charts/ks-devops/crds/gitops.kubesphere.io_applications.yaml, hack/fetch-crds.sh
=> Add the CRD of the application

charts/ks-devops/crds/devops.kubesphere.io_clustertemplates.yaml, charts/ks-devops/crds/devops.kubesphere.io_templates.yaml
Re-sync template CRDs from https://github.com/kubesphere/ks-devops using `hack/fetch-crds.sh`.
See https://github.com/kubesphere/ks-devops/pull/489 for more.
=> Re-sync template CRDs

charts/ks-devops/crds/gitops.kubesphere.io_applications.yaml
Update application.gitops.kubesphere.io CRD using fetch-crds.sh. See 
- https://github.com/kubesphere/ks-devops/pull/502
for more.
/cc @kubesphere-sigs/sig-devops 
/kind chore
=> Update CRDs using fetch-crds.sh

README.md, charts/ks-devops/Chart.yaml, charts/ks-devops/crds/devops.kubesphere.io_gitrepositories.yaml, charts/ks-devops/crds/gitops.kubesphere.io_applications.yaml, charts/ks-devops/templates/deployment-apiserver.yaml, charts/ks-devops/templates/deployment-controller.yaml, charts/ks-devops/templates/serviceaccount.yaml, charts/ks-devops/values.yaml, hack/fetch-crds.sh
=> Add Argo CD installation support

charts/ks-devops/Chart.yaml, charts/ks-devops/charts/s2i/Chart.yaml, charts/ks-devops/charts/s2i/values.yaml
see also https://github.com/kubesphere-sigs/ks-versions/pull/34
=> Bump the tag of image s2ioperator

.github/workflows/pull-request.yaml, charts/ks-devops/Chart.yaml, charts/ks-devops/charts/jenkins/Chart.yaml, charts/ks-devops/charts/jenkins/templates/jenkins-casc-config.yml, charts/ks-devops/charts/jenkins/values.yaml
The upstream PR is https://github.com/kubesphere/devops-agent/pull/70
=> Add new agents of go 17 and go 18

charts/ks-devops/Chart.yaml, charts/ks-devops/charts/jenkins/Chart.yaml
- Improve the readiness probe of the Jenkins (#76)
- Release a new version of jenkins
=> release jenkins

charts/ks-devops/templates/cluster-template-cicd.yaml
fix: https://github.com/kubesphere-sigs/ks-devops-helm-chart/issues/79
=> fix check cicd clustertemplate jenkinsfile failed

charts/ks-devops/charts/jenkins/templates/jenkins-casc-config.yml
- update value of containerCapStr
=> update value of containerCapStr

charts/ks-devops/Chart.yaml
Reverts kubesphere-sigs/ks-devops-helm-chart#85
=> Revert "release 0.1.16"

OWNERS, charts/ks-devops/crds/devops.kubesphere.io_pipelineruns.yaml
- update owners
- update-crd: add PrinterColumns(id) of pipelinerun
=> update-crd: add PrinterColumns(id) of pipelinerun

charts/ks-devops/templates/deployment-apiserver.yaml
=> Add argocd enable to true for apiserver

charts/ks-devops/templates/deployment-apiserver.yaml, charts/ks-devops/templates/deployment-controller.yaml
- fix the bug that pipelinerun not run created by a new user
=> update init container to init-config

charts/ks-devops/Chart.yaml, charts/ks-devops/charts/jenkins/values.yaml, charts/ks-devops/crds/devops.kubesphere.io_clustersteptemplates.yaml, charts/ks-devops/crds/devops.kubesphere.io_gitrepositories.yaml, charts/ks-devops/templates/cluster-step-templates.yaml
https://github.com/kubesphere/issues/issues/985
=> update step-template and crd-gitrepo to re-use code-repo 

charts/ks-devops/templates/cluster-step-templates.yaml
fix: the reactions in step git and checkout not work well
=> bugfix: the reactions not work well

charts/ks-devops/templates/cronjob-gc.yaml
remove un-used args of gc pipelineruns in project
=> remove un-used args of gc pipelineruns in project

charts/ks-devops/templates/_helpers.tpl, charts/ks-devops/templates/cronjob-gc.yaml
fix: setup cronjob apiversion failed
reference: 
https://ask.kubesphere.io/forum/d/22671-awsde-eskqi-yong-cha-jian-kubesphere-devopsyi-chang-namespaces-kubesphere-devops-worker-not-found/20
=> bugfix: setup cronjob apiversion failed

charts/ks-devops/templates/cluster-step-templates.yaml
Fix https://github.com/kubesphere/ks-devops/issues/947
=> Fix double quotation error

charts/ks-devops/templates/cluster-step-templates.yaml
fix: kubesphere/ks-devops#1007
```release-note
fix render error of timeout
```
=> fix 1007 timeout
